import { FactorVector } from '../../common/divination-module.interface';

export interface TarotCard {
  id: number;
  name: string;
  arcana: 'major' | 'minor';
  suit?: string;
  uprightMeaning: string;
  reversedMeaning: string;
  uprightVector: FactorVector;
  reversedVector: FactorVector;
}

// Simplified tarot deck with major arcana + representative minor arcana
export const TAROT_DECK: TarotCard[] = [
  {
    id: 0,
    name: 'The Fool',
    arcana: 'major',
    uprightMeaning: 'New beginnings, innocence, spontaneity, free spirit',
    reversedMeaning: 'Recklessness, taken advantage of, inconsideration',
    uprightVector: { stability: 0.2, change: 0.9, risk: 0.7, safety: 0.3, innerGrowth: 0.8, externalReward: 0.4, emotionalIntensity: 0.7, socialConnection: 0.5 },
    reversedVector: { stability: 0.1, change: 0.5, risk: 0.9, safety: 0.1, innerGrowth: 0.3, externalReward: 0.2, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
  {
    id: 1,
    name: 'The Magician',
    arcana: 'major',
    uprightMeaning: 'Manifestation, resourcefulness, power, inspired action',
    reversedMeaning: 'Manipulation, poor planning, untapped talents',
    uprightVector: { stability: 0.5, change: 0.8, risk: 0.4, safety: 0.6, innerGrowth: 0.7, externalReward: 0.9, emotionalIntensity: 0.6, socialConnection: 0.6 },
    reversedVector: { stability: 0.3, change: 0.4, risk: 0.7, safety: 0.3, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.7, socialConnection: 0.4 },
  },
  {
    id: 2,
    name: 'The High Priestess',
    arcana: 'major',
    uprightMeaning: 'Intuition, sacred knowledge, divine feminine, subconscious',
    reversedMeaning: 'Secrets, disconnected from intuition, withdrawal',
    uprightVector: { stability: 0.6, change: 0.4, risk: 0.3, safety: 0.7, innerGrowth: 0.9, externalReward: 0.4, emotionalIntensity: 0.7, socialConnection: 0.5 },
    reversedVector: { stability: 0.4, change: 0.3, risk: 0.6, safety: 0.4, innerGrowth: 0.5, externalReward: 0.3, emotionalIntensity: 0.8, socialConnection: 0.3 },
  },
  {
    id: 3,
    name: 'The Empress',
    arcana: 'major',
    uprightMeaning: 'Femininity, beauty, nature, nurturing, abundance',
    reversedMeaning: 'Creative block, dependence on others',
    uprightVector: { stability: 0.7, change: 0.5, risk: 0.2, safety: 0.8, innerGrowth: 0.6, externalReward: 0.8, emotionalIntensity: 0.8, socialConnection: 0.9 },
    reversedVector: { stability: 0.3, change: 0.3, risk: 0.5, safety: 0.4, innerGrowth: 0.4, externalReward: 0.4, emotionalIntensity: 0.7, socialConnection: 0.5 },
  },
  {
    id: 4,
    name: 'The Emperor',
    arcana: 'major',
    uprightMeaning: 'Authority, establishment, structure, father figure',
    reversedMeaning: 'Domination, excessive control, lack of discipline',
    uprightVector: { stability: 0.9, change: 0.3, risk: 0.3, safety: 0.8, innerGrowth: 0.5, externalReward: 0.9, emotionalIntensity: 0.4, socialConnection: 0.7 },
    reversedVector: { stability: 0.4, change: 0.5, risk: 0.7, safety: 0.3, innerGrowth: 0.3, externalReward: 0.5, emotionalIntensity: 0.7, socialConnection: 0.4 },
  },
  {
    id: 5,
    name: 'The Lovers',
    arcana: 'major',
    uprightMeaning: 'Love, harmony, relationships, values alignment',
    reversedMeaning: 'Self-love, disharmony, imbalance, misalignment',
    uprightVector: { stability: 0.6, change: 0.6, risk: 0.3, safety: 0.7, innerGrowth: 0.7, externalReward: 0.6, emotionalIntensity: 0.9, socialConnection: 0.9 },
    reversedVector: { stability: 0.3, change: 0.5, risk: 0.6, safety: 0.4, innerGrowth: 0.6, externalReward: 0.3, emotionalIntensity: 0.7, socialConnection: 0.4 },
  },
  {
    id: 6,
    name: 'The Chariot',
    arcana: 'major',
    uprightMeaning: 'Control, willpower, success, determination',
    reversedMeaning: 'Self-discipline, opposition, lack of direction',
    uprightVector: { stability: 0.5, change: 0.8, risk: 0.5, safety: 0.5, innerGrowth: 0.7, externalReward: 0.9, emotionalIntensity: 0.7, socialConnection: 0.5 },
    reversedVector: { stability: 0.2, change: 0.4, risk: 0.8, safety: 0.2, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
  {
    id: 7,
    name: 'Strength',
    arcana: 'major',
    uprightMeaning: 'Courage, persuasion, influence, compassion',
    reversedMeaning: 'Inner strength, self-doubt, low energy, raw emotion',
    uprightVector: { stability: 0.7, change: 0.6, risk: 0.3, safety: 0.7, innerGrowth: 0.8, externalReward: 0.7, emotionalIntensity: 0.8, socialConnection: 0.7 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.6, safety: 0.4, innerGrowth: 0.6, externalReward: 0.4, emotionalIntensity: 0.7, socialConnection: 0.5 },
  },
  {
    id: 8,
    name: 'The Hermit',
    arcana: 'major',
    uprightMeaning: 'Soul searching, introspection, inner guidance',
    reversedMeaning: 'Isolation, loneliness, withdrawal',
    uprightVector: { stability: 0.6, change: 0.4, risk: 0.2, safety: 0.7, innerGrowth: 0.9, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.2 },
    reversedVector: { stability: 0.3, change: 0.3, risk: 0.5, safety: 0.4, innerGrowth: 0.5, externalReward: 0.2, emotionalIntensity: 0.7, socialConnection: 0.1 },
  },
  {
    id: 9,
    name: 'Wheel of Fortune',
    arcana: 'major',
    uprightMeaning: 'Good luck, karma, life cycles, destiny',
    reversedMeaning: 'Bad luck, resistance to change, breaking cycles',
    uprightVector: { stability: 0.4, change: 0.9, risk: 0.5, safety: 0.5, innerGrowth: 0.7, externalReward: 0.8, emotionalIntensity: 0.6, socialConnection: 0.6 },
    reversedVector: { stability: 0.3, change: 0.6, risk: 0.7, safety: 0.3, innerGrowth: 0.5, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  // Add Ace through King for each suit (simplified - just Aces and representative court cards)
  {
    id: 22,
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Inspiration, new opportunities, growth, potential',
    reversedMeaning: 'Emerging idea, lack of direction, distractions',
    uprightVector: { stability: 0.4, change: 0.8, risk: 0.4, safety: 0.6, innerGrowth: 0.7, externalReward: 0.7, emotionalIntensity: 0.7, socialConnection: 0.5 },
    reversedVector: { stability: 0.3, change: 0.4, risk: 0.5, safety: 0.4, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },
  {
    id: 23,
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Love, new relationships, compassion, creativity',
    reversedMeaning: 'Self-love, intuition, repressed emotions',
    uprightVector: { stability: 0.5, change: 0.7, risk: 0.3, safety: 0.7, innerGrowth: 0.7, externalReward: 0.5, emotionalIntensity: 0.9, socialConnection: 0.8 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.4, safety: 0.5, innerGrowth: 0.6, externalReward: 0.3, emotionalIntensity: 0.7, socialConnection: 0.4 },
  },
  {
    id: 24,
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Breakthroughs, new ideas, mental clarity, success',
    reversedMeaning: 'Inner clarity, re-thinking an idea, clouded judgment',
    uprightVector: { stability: 0.3, change: 0.8, risk: 0.6, safety: 0.4, innerGrowth: 0.8, externalReward: 0.7, emotionalIntensity: 0.5, socialConnection: 0.5 },
    reversedVector: { stability: 0.3, change: 0.5, risk: 0.6, safety: 0.4, innerGrowth: 0.6, externalReward: 0.4, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 25,
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Opportunity, prosperity, new venture',
    reversedMeaning: 'Lost opportunity, missed chance, bad investment',
    uprightVector: { stability: 0.7, change: 0.6, risk: 0.3, safety: 0.7, innerGrowth: 0.5, externalReward: 0.9, emotionalIntensity: 0.4, socialConnection: 0.6 },
    reversedVector: { stability: 0.3, change: 0.3, risk: 0.7, safety: 0.3, innerGrowth: 0.3, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.4 },
  },
  // ... (Your existing code ending at id: 25 Ace of Pentacles)

  // --- REMAINING MAJOR ARCANA (10-21) ---
  {
    id: 10,
    name: 'The Hierophant',
    arcana: 'major',
    uprightMeaning: 'Spiritual wisdom, religious beliefs, conformity, tradition',
    reversedMeaning: 'Personal beliefs, freedom, challenging the status quo',
    uprightVector: { stability: 0.9, change: 0.2, risk: 0.2, safety: 0.8, innerGrowth: 0.7, externalReward: 0.5, emotionalIntensity: 0.4, socialConnection: 0.9 },
    reversedVector: { stability: 0.4, change: 0.7, risk: 0.6, safety: 0.3, innerGrowth: 0.8, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },
  {
    id: 11,
    name: 'Justice',
    arcana: 'major',
    uprightMeaning: 'Justice, fairness, truth, cause and effect, law',
    reversedMeaning: 'Unfairness, lack of accountability, dishonesty',
    uprightVector: { stability: 0.8, change: 0.5, risk: 0.3, safety: 0.6, innerGrowth: 0.6, externalReward: 0.5, emotionalIntensity: 0.4, socialConnection: 0.5 },
    reversedVector: { stability: 0.3, change: 0.4, risk: 0.7, safety: 0.2, innerGrowth: 0.2, externalReward: 0.1, emotionalIntensity: 0.6, socialConnection: 0.2 },
  },
  {
    id: 12,
    name: 'The Hanged Man',
    arcana: 'major',
    uprightMeaning: 'Pause, surrender, letting go, new perspective',
    reversedMeaning: 'Delays, resistance, stalling, indecision',
    uprightVector: { stability: 0.4, change: 0.6, risk: 0.5, safety: 0.4, innerGrowth: 0.9, externalReward: 0.1, emotionalIntensity: 0.5, socialConnection: 0.2 },
    reversedVector: { stability: 0.2, change: 0.3, risk: 0.6, safety: 0.2, innerGrowth: 0.3, externalReward: 0.1, emotionalIntensity: 0.6, socialConnection: 0.2 },
  },
  {
    id: 13,
    name: 'Death',
    arcana: 'major',
    uprightMeaning: 'Endings, change, transformation, transition',
    reversedMeaning: 'Resistance to change, personal transformation, inability to move on',
    uprightVector: { stability: 0.1, change: 1.0, risk: 0.8, safety: 0.1, innerGrowth: 0.8, externalReward: 0.2, emotionalIntensity: 0.9, socialConnection: 0.3 },
    reversedVector: { stability: 0.5, change: 0.2, risk: 0.4, safety: 0.4, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.7, socialConnection: 0.3 },
  },
  {
    id: 14,
    name: 'Temperance',
    arcana: 'major',
    uprightMeaning: 'Balance, moderation, patience, purpose',
    reversedMeaning: 'Imbalance, excess, self-healing, re-alignment',
    uprightVector: { stability: 0.8, change: 0.4, risk: 0.2, safety: 0.8, innerGrowth: 0.8, externalReward: 0.5, emotionalIntensity: 0.3, socialConnection: 0.6 },
    reversedVector: { stability: 0.3, change: 0.6, risk: 0.5, safety: 0.3, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 15,
    name: 'The Devil',
    arcana: 'major',
    uprightMeaning: 'Shadow self, attachment, addiction, restriction, sexuality',
    reversedMeaning: 'Releasing limiting beliefs, exploring dark thoughts, detachment',
    uprightVector: { stability: 0.3, change: 0.4, risk: 0.9, safety: 0.1, innerGrowth: 0.3, externalReward: 0.7, emotionalIntensity: 0.9, socialConnection: 0.4 },
    reversedVector: { stability: 0.4, change: 0.7, risk: 0.5, safety: 0.5, innerGrowth: 0.7, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
  {
    id: 16,
    name: 'The Tower',
    arcana: 'major',
    uprightMeaning: 'Sudden change, upheaval, chaos, revelation, awakening',
    reversedMeaning: 'Personal transformation, fear of change, averting disaster',
    uprightVector: { stability: 0.0, change: 1.0, risk: 1.0, safety: 0.0, innerGrowth: 0.6, externalReward: 0.1, emotionalIntensity: 1.0, socialConnection: 0.3 },
    reversedVector: { stability: 0.2, change: 0.5, risk: 0.7, safety: 0.2, innerGrowth: 0.5, externalReward: 0.2, emotionalIntensity: 0.8, socialConnection: 0.3 },
  },
  {
    id: 17,
    name: 'The Star',
    arcana: 'major',
    uprightMeaning: 'Hope, faith, purpose, renewal, spirituality',
    reversedMeaning: 'Lack of faith, despair, self-trust, disconnection',
    uprightVector: { stability: 0.6, change: 0.5, risk: 0.2, safety: 0.7, innerGrowth: 0.9, externalReward: 0.4, emotionalIntensity: 0.6, socialConnection: 0.5 },
    reversedVector: { stability: 0.3, change: 0.3, risk: 0.5, safety: 0.2, innerGrowth: 0.3, externalReward: 0.1, emotionalIntensity: 0.7, socialConnection: 0.2 },
  },
  {
    id: 18,
    name: 'The Moon',
    arcana: 'major',
    uprightMeaning: 'Illusion, fear, anxiety, subconscious, intuition',
    reversedMeaning: 'Release of fear, repressed emotion, inner confusion',
    uprightVector: { stability: 0.3, change: 0.6, risk: 0.7, safety: 0.2, innerGrowth: 0.7, externalReward: 0.2, emotionalIntensity: 0.8, socialConnection: 0.3 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.5, safety: 0.4, innerGrowth: 0.5, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
  {
    id: 19,
    name: 'The Sun',
    arcana: 'major',
    uprightMeaning: 'Positivity, fun, warmth, success, vitality',
    reversedMeaning: 'Inner child, feeling down, overly optimistic',
    uprightVector: { stability: 0.8, change: 0.4, risk: 0.1, safety: 0.9, innerGrowth: 0.7, externalReward: 1.0, emotionalIntensity: 0.7, socialConnection: 0.8 },
    reversedVector: { stability: 0.5, change: 0.3, risk: 0.4, safety: 0.5, innerGrowth: 0.5, externalReward: 0.4, emotionalIntensity: 0.5, socialConnection: 0.5 },
  },
  {
    id: 20,
    name: 'Judgement',
    arcana: 'major',
    uprightMeaning: 'Judgement, rebirth, inner calling, absolution',
    reversedMeaning: 'Self-doubt, inner critic, ignoring the call',
    uprightVector: { stability: 0.5, change: 0.9, risk: 0.6, safety: 0.5, innerGrowth: 1.0, externalReward: 0.5, emotionalIntensity: 0.8, socialConnection: 0.6 },
    reversedVector: { stability: 0.3, change: 0.2, risk: 0.5, safety: 0.3, innerGrowth: 0.3, externalReward: 0.2, emotionalIntensity: 0.7, socialConnection: 0.2 },
  },
  {
    id: 21,
    name: 'The World',
    arcana: 'major',
    uprightMeaning: 'Completion, integration, accomplishment, travel',
    reversedMeaning: 'Seeking personal closure, short-cuts, delays',
    uprightVector: { stability: 0.9, change: 0.3, risk: 0.1, safety: 0.9, innerGrowth: 0.9, externalReward: 1.0, emotionalIntensity: 0.6, socialConnection: 0.8 },
    reversedVector: { stability: 0.5, change: 0.4, risk: 0.4, safety: 0.5, innerGrowth: 0.5, externalReward: 0.4, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },

  // --- MINOR ARCANA: WANDS (Fire: Action, Passion) ---
  // (Assuming Aces are already IDs 22-25. We continue from 26)
  {
    id: 26,
    name: '10 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Burden, extra responsibility, hard work, completion',
    reversedMeaning: 'Doing it all, carrying the burden, delegation',
    uprightVector: { stability: 0.4, change: 0.3, risk: 0.6, safety: 0.3, innerGrowth: 0.5, externalReward: 0.6, emotionalIntensity: 0.8, socialConnection: 0.3 },
    reversedVector: { stability: 0.5, change: 0.4, risk: 0.4, safety: 0.5, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.5 },
  },
  {
    id: 27,
    name: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Inspiration, ideas, discovery, limitless potential',
    reversedMeaning: 'Newly formed ideas, redirecting energy, self-limiting beliefs',
    uprightVector: { stability: 0.3, change: 0.8, risk: 0.6, safety: 0.4, innerGrowth: 0.7, externalReward: 0.4, emotionalIntensity: 0.7, socialConnection: 0.6 },
    reversedVector: { stability: 0.2, change: 0.4, risk: 0.7, safety: 0.2, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },
  {
    id: 28,
    name: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Energy, passion, inspired action, adventure, impulsiveness',
    reversedMeaning: 'Passion project, haste, scattered energy, delays',
    uprightVector: { stability: 0.2, change: 0.9, risk: 0.8, safety: 0.2, innerGrowth: 0.5, externalReward: 0.6, emotionalIntensity: 0.8, socialConnection: 0.5 },
    reversedVector: { stability: 0.1, change: 0.5, risk: 0.9, safety: 0.1, innerGrowth: 0.3, externalReward: 0.3, emotionalIntensity: 0.7, socialConnection: 0.3 },
  },
  {
    id: 29,
    name: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Courage, confidence, independence, social butterfly, determination',
    reversedMeaning: 'Self-respect, self-confidence, introverted, re-establishing sense of self',
    uprightVector: { stability: 0.6, change: 0.6, risk: 0.4, safety: 0.6, innerGrowth: 0.7, externalReward: 0.7, emotionalIntensity: 0.7, socialConnection: 0.9 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.5, safety: 0.4, innerGrowth: 0.6, externalReward: 0.4, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 30,
    name: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Natural-born leader, vision, entrepreneur, honor',
    reversedMeaning: 'Impulsiveness, haste, ruthless, high expectations',
    uprightVector: { stability: 0.7, change: 0.7, risk: 0.5, safety: 0.6, innerGrowth: 0.6, externalReward: 0.9, emotionalIntensity: 0.6, socialConnection: 0.8 },
    reversedVector: { stability: 0.4, change: 0.5, risk: 0.7, safety: 0.3, innerGrowth: 0.4, externalReward: 0.5, emotionalIntensity: 0.7, socialConnection: 0.5 },
  },

  // --- MINOR ARCANA: CUPS (Water: Emotion, Relationships) ---
  {
    id: 31,
    name: '10 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Divine love, blissful relationships, harmony, alignment',
    reversedMeaning: 'Disconnection, misaligned values, struggling relationships',
    uprightVector: { stability: 0.8, change: 0.2, risk: 0.1, safety: 0.9, innerGrowth: 0.7, externalReward: 0.8, emotionalIntensity: 0.9, socialConnection: 1.0 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.4, safety: 0.3, innerGrowth: 0.5, externalReward: 0.3, emotionalIntensity: 0.7, socialConnection: 0.3 },
  },
  {
    id: 32,
    name: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Creative opportunity, intuitive messages, curiosity',
    reversedMeaning: 'New ideas, doubting intuition, creative blocks',
    uprightVector: { stability: 0.4, change: 0.6, risk: 0.3, safety: 0.6, innerGrowth: 0.7, externalReward: 0.3, emotionalIntensity: 0.8, socialConnection: 0.6 },
    reversedVector: { stability: 0.3, change: 0.3, risk: 0.4, safety: 0.4, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
  {
    id: 33,
    name: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Creativity, romance, charm, imagination, beauty',
    reversedMeaning: 'Overactive imagination, unrealistic, jealous, moody',
    uprightVector: { stability: 0.4, change: 0.6, risk: 0.4, safety: 0.5, innerGrowth: 0.6, externalReward: 0.5, emotionalIntensity: 0.9, socialConnection: 0.7 },
    reversedVector: { stability: 0.2, change: 0.4, risk: 0.5, safety: 0.2, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.8, socialConnection: 0.4 },
  },
  {
    id: 34,
    name: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Compassionate, caring, emotionally stable, intuitive',
    reversedMeaning: 'Inner feelings, self-care, self-love, co-dependency',
    uprightVector: { stability: 0.7, change: 0.3, risk: 0.2, safety: 0.8, innerGrowth: 0.8, externalReward: 0.4, emotionalIntensity: 0.8, socialConnection: 0.9 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.4, safety: 0.4, innerGrowth: 0.6, externalReward: 0.2, emotionalIntensity: 0.9, socialConnection: 0.5 },
  },
  {
    id: 35,
    name: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Emotionally balanced, compassionate, diplomatic',
    reversedMeaning: 'Self-compassion, inner feelings, moodiness, emotionally manipulative',
    uprightVector: { stability: 0.8, change: 0.3, risk: 0.2, safety: 0.8, innerGrowth: 0.8, externalReward: 0.7, emotionalIntensity: 0.6, socialConnection: 0.8 },
    reversedVector: { stability: 0.4, change: 0.5, risk: 0.5, safety: 0.3, innerGrowth: 0.5, externalReward: 0.3, emotionalIntensity: 0.8, socialConnection: 0.4 },
  },

  // --- MINOR ARCANA: SWORDS (Air: Intellect, Conflict) ---
  {
    id: 36,
    name: '10 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Painful endings, deep wounds, betrayal, loss, crisis',
    reversedMeaning: 'Recovery, regeneration, resisting an inevitable end',
    uprightVector: { stability: 0.1, change: 0.9, risk: 0.9, safety: 0.0, innerGrowth: 0.5, externalReward: 0.0, emotionalIntensity: 1.0, socialConnection: 0.2 },
    reversedVector: { stability: 0.3, change: 0.5, risk: 0.6, safety: 0.3, innerGrowth: 0.6, externalReward: 0.2, emotionalIntensity: 0.7, socialConnection: 0.3 },
  },
  {
    id: 37,
    name: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'New ideas, curiosity, thirst for knowledge, new ways of communicating',
    reversedMeaning: 'Self-expression, all talk and no action, haphazard action',
    uprightVector: { stability: 0.3, change: 0.7, risk: 0.6, safety: 0.4, innerGrowth: 0.6, externalReward: 0.4, emotionalIntensity: 0.5, socialConnection: 0.5 },
    reversedVector: { stability: 0.2, change: 0.4, risk: 0.7, safety: 0.2, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.6, socialConnection: 0.2 },
  },
  {
    id: 38,
    name: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Ambitious, action-oriented, driven to succeed, fast-thinking',
    reversedMeaning: 'Restless, unfocused, impulsive, burn-out',
    uprightVector: { stability: 0.3, change: 0.9, risk: 0.8, safety: 0.3, innerGrowth: 0.5, externalReward: 0.7, emotionalIntensity: 0.6, socialConnection: 0.4 },
    reversedVector: { stability: 0.2, change: 0.5, risk: 0.8, safety: 0.2, innerGrowth: 0.3, externalReward: 0.3, emotionalIntensity: 0.7, socialConnection: 0.2 },
  },
  {
    id: 39,
    name: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Independent, unbiased judgement, clear boundaries, direct communication',
    reversedMeaning: 'Overly-emotional, easily influenced, bitchy, cold',
    uprightVector: { stability: 0.7, change: 0.4, risk: 0.4, safety: 0.6, innerGrowth: 0.7, externalReward: 0.6, emotionalIntensity: 0.4, socialConnection: 0.5 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.5, safety: 0.3, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.8, socialConnection: 0.3 },
  },
  {
    id: 40,
    name: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Mental clarity, intellectual power, authority, truth',
    reversedMeaning: 'Quiet power, inner truth, misuse of power, manipulation',
    uprightVector: { stability: 0.8, change: 0.4, risk: 0.3, safety: 0.7, innerGrowth: 0.7, externalReward: 0.8, emotionalIntensity: 0.3, socialConnection: 0.6 },
    reversedVector: { stability: 0.5, change: 0.5, risk: 0.6, safety: 0.4, innerGrowth: 0.5, externalReward: 0.5, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },

  // --- MINOR ARCANA: PENTACLES (Earth: Material, Career) ---
  {
    id: 41,
    name: '10 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Wealth, financial security, family, long-term success, contribution',
    reversedMeaning: 'The dark side of wealth, financial failure or loss',
    uprightVector: { stability: 1.0, change: 0.1, risk: 0.1, safety: 1.0, innerGrowth: 0.5, externalReward: 1.0, emotionalIntensity: 0.4, socialConnection: 0.9 },
    reversedVector: { stability: 0.4, change: 0.5, risk: 0.7, safety: 0.3, innerGrowth: 0.3, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 42,
    name: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Manifestation, financial opportunity, skill development',
    reversedMeaning: 'Lack of progress, procrastination, learn from failure',
    uprightVector: { stability: 0.6, change: 0.4, risk: 0.2, safety: 0.7, innerGrowth: 0.6, externalReward: 0.5, emotionalIntensity: 0.4, socialConnection: 0.4 },
    reversedVector: { stability: 0.4, change: 0.3, risk: 0.4, safety: 0.4, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },
  {
    id: 43,
    name: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Hard work, productivity, routine, conservatism',
    reversedMeaning: 'Self-discipline, boredom, feeling "stuck", perfectionism',
    uprightVector: { stability: 0.8, change: 0.1, risk: 0.1, safety: 0.8, innerGrowth: 0.4, externalReward: 0.6, emotionalIntensity: 0.3, socialConnection: 0.4 },
    reversedVector: { stability: 0.5, change: 0.2, risk: 0.3, safety: 0.5, innerGrowth: 0.3, externalReward: 0.3, emotionalIntensity: 0.4, socialConnection: 0.3 },
  },
  {
    id: 44,
    name: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Nurturing, practical, providing financially, a working parent',
    reversedMeaning: 'Financial independence, self-care, work-home conflict',
    uprightVector: { stability: 0.9, change: 0.2, risk: 0.1, safety: 0.9, innerGrowth: 0.6, externalReward: 0.8, emotionalIntensity: 0.6, socialConnection: 0.8 },
    reversedVector: { stability: 0.5, change: 0.4, risk: 0.4, safety: 0.5, innerGrowth: 0.5, externalReward: 0.4, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 45,
    name: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Wealth, business, leadership, security, discipline, abundance',
    reversedMeaning: 'Financially inept, obsessed with wealth and status, stubborn',
    uprightVector: { stability: 1.0, change: 0.1, risk: 0.1, safety: 0.9, innerGrowth: 0.5, externalReward: 1.0, emotionalIntensity: 0.3, socialConnection: 0.7 },
    reversedVector: { stability: 0.6, change: 0.3, risk: 0.6, safety: 0.5, innerGrowth: 0.3, externalReward: 0.5, emotionalIntensity: 0.5, socialConnection: 0.4 },
  },
// --- WANDS (2-9) ---
  {
    id: 46,
    name: '2 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Future planning, progress, decisions, discovery',
    reversedMeaning: 'Fear of unknown, lack of planning',
    uprightVector: { stability: 0.5, change: 0.6, risk: 0.4, safety: 0.5, innerGrowth: 0.6, externalReward: 0.5, emotionalIntensity: 0.4, socialConnection: 0.3 },
    reversedVector: { stability: 0.3, change: 0.3, risk: 0.6, safety: 0.3, innerGrowth: 0.3, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.2 },
  },
  {
    id: 47,
    name: '3 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Expansion, foresight, overseas opportunities',
    reversedMeaning: 'Playing small, lack of foresight, unexpected delays',
    uprightVector: { stability: 0.4, change: 0.7, risk: 0.5, safety: 0.4, innerGrowth: 0.6, externalReward: 0.7, emotionalIntensity: 0.5, socialConnection: 0.4 },
    reversedVector: { stability: 0.3, change: 0.4, risk: 0.5, safety: 0.4, innerGrowth: 0.3, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
  {
    id: 48,
    name: '4 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Celebration, joy, harmony, relaxation, homecoming',
    reversedMeaning: 'Personal celebration, inner harmony, conflict with family',
    uprightVector: { stability: 0.8, change: 0.2, risk: 0.1, safety: 0.9, innerGrowth: 0.5, externalReward: 0.6, emotionalIntensity: 0.7, socialConnection: 0.9 },
    reversedVector: { stability: 0.5, change: 0.4, risk: 0.4, safety: 0.5, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.5 },
  },
  {
    id: 49,
    name: '5 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Conflict, disagreements, competition, tension',
    reversedMeaning: 'Conflict avoidance, diversity of opinion, agreeing to disagree',
    uprightVector: { stability: 0.2, change: 0.7, risk: 0.6, safety: 0.3, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.8, socialConnection: 0.4 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.4, safety: 0.5, innerGrowth: 0.5, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.5 },
  },
  {
    id: 50,
    name: '6 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Success, public recognition, progress, self-confidence',
    reversedMeaning: 'Egotism, fall from grace, lack of recognition',
    uprightVector: { stability: 0.6, change: 0.5, risk: 0.3, safety: 0.6, innerGrowth: 0.6, externalReward: 0.9, emotionalIntensity: 0.7, socialConnection: 0.8 },
    reversedVector: { stability: 0.3, change: 0.4, risk: 0.5, safety: 0.3, innerGrowth: 0.3, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 51,
    name: '7 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Challenge, competition, protection, perseverance',
    reversedMeaning: 'Giving up, overwhelmed, overly protective',
    uprightVector: { stability: 0.5, change: 0.6, risk: 0.7, safety: 0.4, innerGrowth: 0.7, externalReward: 0.5, emotionalIntensity: 0.8, socialConnection: 0.2 },
    reversedVector: { stability: 0.2, change: 0.4, risk: 0.8, safety: 0.2, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.7, socialConnection: 0.2 },
  },
  {
    id: 52,
    name: '8 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Movement, fast paced change, action, alignment',
    reversedMeaning: 'Delays, frustration, resisting change, panic',
    uprightVector: { stability: 0.2, change: 0.9, risk: 0.6, safety: 0.3, innerGrowth: 0.4, externalReward: 0.6, emotionalIntensity: 0.6, socialConnection: 0.5 },
    reversedVector: { stability: 0.2, change: 0.3, risk: 0.7, safety: 0.2, innerGrowth: 0.3, externalReward: 0.2, emotionalIntensity: 0.8, socialConnection: 0.3 },
  },
  {
    id: 53,
    name: '9 of Wands',
    arcana: 'minor',
    suit: 'wands',
    uprightMeaning: 'Resilience, courage, persistence, test of faith',
    reversedMeaning: 'Inner struggles, overwhelm, defensive, paranoia',
    uprightVector: { stability: 0.6, change: 0.3, risk: 0.5, safety: 0.5, innerGrowth: 0.8, externalReward: 0.4, emotionalIntensity: 0.7, socialConnection: 0.2 },
    reversedVector: { stability: 0.3, change: 0.4, risk: 0.6, safety: 0.2, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.8, socialConnection: 0.1 },
  },

  // --- CUPS (2-9) ---
  {
    id: 54,
    name: '2 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Unified love, partnership, mutual attraction',
    reversedMeaning: 'Self-love, break-ups, disharmony, distrust',
    uprightVector: { stability: 0.7, change: 0.4, risk: 0.2, safety: 0.8, innerGrowth: 0.6, externalReward: 0.5, emotionalIntensity: 0.9, socialConnection: 1.0 },
    reversedVector: { stability: 0.3, change: 0.6, risk: 0.5, safety: 0.3, innerGrowth: 0.5, externalReward: 0.2, emotionalIntensity: 0.8, socialConnection: 0.2 },
  },
  {
    id: 55,
    name: '3 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Celebration, friendship, creativity, collaborations',
    reversedMeaning: 'Independence, alone time, gossip, isolation',
    uprightVector: { stability: 0.6, change: 0.3, risk: 0.2, safety: 0.7, innerGrowth: 0.4, externalReward: 0.4, emotionalIntensity: 0.8, socialConnection: 0.9 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.3, safety: 0.4, innerGrowth: 0.5, externalReward: 0.2, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
  {
    id: 56,
    name: '4 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Meditation, contemplation, apathy, re-evaluation',
    reversedMeaning: 'Retreat, withdrawal, checking in for alignment',
    uprightVector: { stability: 0.5, change: 0.1, risk: 0.1, safety: 0.6, innerGrowth: 0.7, externalReward: 0.2, emotionalIntensity: 0.4, socialConnection: 0.2 },
    reversedVector: { stability: 0.4, change: 0.3, risk: 0.2, safety: 0.4, innerGrowth: 0.6, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },
  {
    id: 57,
    name: '5 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Regret, failure, disappointment, pessimism',
    reversedMeaning: 'Personal setbacks, self-forgiveness, moving on',
    uprightVector: { stability: 0.2, change: 0.4, risk: 0.4, safety: 0.2, innerGrowth: 0.5, externalReward: 0.1, emotionalIntensity: 0.9, socialConnection: 0.3 },
    reversedVector: { stability: 0.3, change: 0.5, risk: 0.3, safety: 0.4, innerGrowth: 0.7, externalReward: 0.2, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 58,
    name: '6 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Revisiting the past, childhood memories, innocence, joy',
    reversedMeaning: 'Living in the past, forgiveness, lacking playfulness',
    uprightVector: { stability: 0.7, change: 0.2, risk: 0.1, safety: 0.8, innerGrowth: 0.5, externalReward: 0.3, emotionalIntensity: 0.7, socialConnection: 0.7 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.3, safety: 0.4, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.4 },
  },
  {
    id: 59,
    name: '7 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Opportunities, choices, wishful thinking, illusion',
    reversedMeaning: 'Alignment, personal values, overwhelmed by choices',
    uprightVector: { stability: 0.3, change: 0.6, risk: 0.6, safety: 0.3, innerGrowth: 0.5, externalReward: 0.5, emotionalIntensity: 0.6, socialConnection: 0.4 },
    reversedVector: { stability: 0.5, change: 0.3, risk: 0.3, safety: 0.6, innerGrowth: 0.6, externalReward: 0.3, emotionalIntensity: 0.4, socialConnection: 0.3 },
  },
  {
    id: 60,
    name: '8 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Disappointment, abandonment, withdrawal, escapism',
    reversedMeaning: 'Trying one more time, indecision, aimless drifting',
    uprightVector: { stability: 0.2, change: 0.8, risk: 0.6, safety: 0.1, innerGrowth: 0.8, externalReward: 0.1, emotionalIntensity: 0.7, socialConnection: 0.1 },
    reversedVector: { stability: 0.3, change: 0.3, risk: 0.5, safety: 0.3, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.6, socialConnection: 0.2 },
  },
  {
    id: 61,
    name: '9 of Cups',
    arcana: 'minor',
    suit: 'cups',
    uprightMeaning: 'Contentment, satisfaction, gratitude, wish come true',
    reversedMeaning: 'Inner happiness, materialism, dissatisfaction',
    uprightVector: { stability: 0.8, change: 0.2, risk: 0.1, safety: 0.8, innerGrowth: 0.6, externalReward: 0.9, emotionalIntensity: 0.7, socialConnection: 0.5 },
    reversedVector: { stability: 0.5, change: 0.3, risk: 0.3, safety: 0.5, innerGrowth: 0.5, externalReward: 0.4, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },

  // --- SWORDS (2-9) ---
  {
    id: 62,
    name: '2 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Difficult decisions, weighing options, an impasse, avoidance',
    reversedMeaning: 'Indecision, confusion, information overload',
    uprightVector: { stability: 0.5, change: 0.2, risk: 0.4, safety: 0.4, innerGrowth: 0.5, externalReward: 0.2, emotionalIntensity: 0.4, socialConnection: 0.3 },
    reversedVector: { stability: 0.3, change: 0.5, risk: 0.5, safety: 0.3, innerGrowth: 0.4, externalReward: 0.1, emotionalIntensity: 0.6, socialConnection: 0.2 },
  },
  {
    id: 63,
    name: '3 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Heartbreak, emotional pain, sorrow, grief, hurt',
    reversedMeaning: 'Negative self-talk, releasing pain, optimism, forgiveness',
    uprightVector: { stability: 0.2, change: 0.6, risk: 0.5, safety: 0.1, innerGrowth: 0.7, externalReward: 0.1, emotionalIntensity: 1.0, socialConnection: 0.2 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.3, safety: 0.4, innerGrowth: 0.8, externalReward: 0.2, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
  {
    id: 64,
    name: '4 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Rest, relaxation, meditation, contemplation, recuperation',
    reversedMeaning: 'Exhaustion, burn-out, deep contemplation',
    uprightVector: { stability: 0.8, change: 0.1, risk: 0.1, safety: 0.9, innerGrowth: 0.7, externalReward: 0.1, emotionalIntensity: 0.2, socialConnection: 0.1 },
    reversedVector: { stability: 0.4, change: 0.3, risk: 0.4, safety: 0.3, innerGrowth: 0.5, externalReward: 0.1, emotionalIntensity: 0.6, socialConnection: 0.2 },
  },
  {
    id: 65,
    name: '5 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Conflict, disagreements, competition, defeat, winning at all costs',
    reversedMeaning: 'Reconciliation, making amends, past resentment',
    uprightVector: { stability: 0.2, change: 0.6, risk: 0.7, safety: 0.1, innerGrowth: 0.3, externalReward: 0.4, emotionalIntensity: 0.7, socialConnection: 0.2 },
    reversedVector: { stability: 0.4, change: 0.5, risk: 0.4, safety: 0.4, innerGrowth: 0.6, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.5 },
  },
  {
    id: 66,
    name: '6 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Transition, change, rite of passage, releasing baggage',
    reversedMeaning: 'Personal transition, resistance to change, unfinished business',
    uprightVector: { stability: 0.4, change: 0.8, risk: 0.5, safety: 0.4, innerGrowth: 0.6, externalReward: 0.3, emotionalIntensity: 0.5, socialConnection: 0.4 },
    reversedVector: { stability: 0.3, change: 0.3, risk: 0.6, safety: 0.3, innerGrowth: 0.4, externalReward: 0.2, emotionalIntensity: 0.7, socialConnection: 0.3 },
  },
  {
    id: 67,
    name: '7 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Betrayal, deception, getting away with something, acting blindly',
    reversedMeaning: 'Imposter syndrome, self-deceit, keeping secrets',
    uprightVector: { stability: 0.3, change: 0.5, risk: 0.8, safety: 0.2, innerGrowth: 0.3, externalReward: 0.4, emotionalIntensity: 0.6, socialConnection: 0.2 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.5, safety: 0.3, innerGrowth: 0.6, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.2 },
  },
  {
    id: 68,
    name: '8 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Negative thoughts, self-imposed restriction, imprisonment, victim mentality',
    reversedMeaning: 'Self-acceptance, new perspectives, freedom',
    uprightVector: { stability: 0.2, change: 0.1, risk: 0.7, safety: 0.1, innerGrowth: 0.2, externalReward: 0.1, emotionalIntensity: 0.8, socialConnection: 0.2 },
    reversedVector: { stability: 0.4, change: 0.6, risk: 0.4, safety: 0.5, innerGrowth: 0.8, externalReward: 0.2, emotionalIntensity: 0.5, socialConnection: 0.4 },
  },
  {
    id: 69,
    name: '9 of Swords',
    arcana: 'minor',
    suit: 'swords',
    uprightMeaning: 'Anxiety, worry, fear, depression, nightmares',
    reversedMeaning: 'Inner turmoil, deep-seated fears, secrets, releasing worry',
    uprightVector: { stability: 0.1, change: 0.2, risk: 0.6, safety: 0.1, innerGrowth: 0.4, externalReward: 0.1, emotionalIntensity: 0.9, socialConnection: 0.2 },
    reversedVector: { stability: 0.3, change: 0.4, risk: 0.4, safety: 0.3, innerGrowth: 0.7, externalReward: 0.2, emotionalIntensity: 0.7, socialConnection: 0.3 },
  },

  // --- PENTACLES (2-9) ---
  {
    id: 70,
    name: '2 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Multiple priorities, time management, adaptability, flow',
    reversedMeaning: 'Over-committed, disorganization, reprioritization',
    uprightVector: { stability: 0.4, change: 0.7, risk: 0.4, safety: 0.4, innerGrowth: 0.5, externalReward: 0.6, emotionalIntensity: 0.4, socialConnection: 0.4 },
    reversedVector: { stability: 0.2, change: 0.5, risk: 0.6, safety: 0.2, innerGrowth: 0.3, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.2 },
  },
  {
    id: 71,
    name: '3 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Teamwork, collaboration, learning, implementation',
    reversedMeaning: 'Disharmony, misalignment, working alone',
    uprightVector: { stability: 0.7, change: 0.4, risk: 0.2, safety: 0.7, innerGrowth: 0.6, externalReward: 0.7, emotionalIntensity: 0.4, socialConnection: 0.8 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.4, safety: 0.4, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },
  {
    id: 72,
    name: '4 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Saving money, security, conservatism, scarcity, control',
    reversedMeaning: 'Over-spending, greed, self-protection',
    uprightVector: { stability: 0.9, change: 0.1, risk: 0.1, safety: 0.8, innerGrowth: 0.3, externalReward: 0.7, emotionalIntensity: 0.4, socialConnection: 0.2 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.6, safety: 0.3, innerGrowth: 0.4, externalReward: 0.4, emotionalIntensity: 0.5, socialConnection: 0.3 },
  },
  {
    id: 73,
    name: '5 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Financial loss, poverty, lack mindset, isolation, worry',
    reversedMeaning: 'Recovery from financial loss, spiritual poverty',
    uprightVector: { stability: 0.1, change: 0.5, risk: 0.8, safety: 0.0, innerGrowth: 0.4, externalReward: 0.1, emotionalIntensity: 0.8, socialConnection: 0.2 },
    reversedVector: { stability: 0.3, change: 0.6, risk: 0.5, safety: 0.2, innerGrowth: 0.6, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 74,
    name: '6 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Giving, receiving, sharing wealth, generosity, charity',
    reversedMeaning: 'Self-care, unpaid debt, one-sided charity',
    uprightVector: { stability: 0.7, change: 0.3, risk: 0.2, safety: 0.7, innerGrowth: 0.6, externalReward: 0.6, emotionalIntensity: 0.5, socialConnection: 0.8 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.4, safety: 0.4, innerGrowth: 0.4, externalReward: 0.3, emotionalIntensity: 0.6, socialConnection: 0.4 },
  },
  {
    id: 75,
    name: '7 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Long-term view, sustainable results, perseverance, investment',
    reversedMeaning: 'Lack of long-term vision, limited success, impatience',
    uprightVector: { stability: 0.6, change: 0.2, risk: 0.3, safety: 0.6, innerGrowth: 0.5, externalReward: 0.6, emotionalIntensity: 0.4, socialConnection: 0.3 },
    reversedVector: { stability: 0.3, change: 0.5, risk: 0.5, safety: 0.3, innerGrowth: 0.3, externalReward: 0.2, emotionalIntensity: 0.6, socialConnection: 0.2 },
  },
  {
    id: 76,
    name: '8 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Apprenticeship, repetitive tasks, mastery, skill development',
    reversedMeaning: 'Self-development, perfectionism, misdirected activity',
    uprightVector: { stability: 0.8, change: 0.2, risk: 0.1, safety: 0.7, innerGrowth: 0.7, externalReward: 0.6, emotionalIntensity: 0.3, socialConnection: 0.2 },
    reversedVector: { stability: 0.4, change: 0.4, risk: 0.3, safety: 0.4, innerGrowth: 0.5, externalReward: 0.3, emotionalIntensity: 0.5, socialConnection: 0.2 },
  },
  {
    id: 77,
    name: '9 of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    uprightMeaning: 'Abundance, luxury, self-sufficiency, financial independence',
    reversedMeaning: 'Self-worth, over-investment in work, hustling',
    uprightVector: { stability: 0.9, change: 0.1, risk: 0.2, safety: 0.9, innerGrowth: 0.7, externalReward: 1.0, emotionalIntensity: 0.5, socialConnection: 0.4 },
    reversedVector: { stability: 0.5, change: 0.3, risk: 0.4, safety: 0.5, innerGrowth: 0.5, externalReward: 0.6, emotionalIntensity: 0.6, socialConnection: 0.3 },
  },
];
